#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch nad_RMX1941-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
ccache -s
	make sepolicy
	mka nad
#sleep 75m
#kill %1 || echo "Build already failed or completed"
ccache -s

# upload
up(){
	curl --upload-file $1 https://transfer.sh/$(basename$1); echo
	# 14 days, 10 GB limit
}


#up(){
#	time rclone copy $1 aosp:ccache/ccache-ci -P # apon is my rclone config name, 
#}
cd /tmp/rom
up /tmp/rom/out/target/product/RMX1941/*UNOFFICIAL*.zip || echo "Only ccache generated or build failed lol"
ccache -s
