#!/bin/bash
cd /tmp/rom/lah # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch nad_RMX1941-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export USE_GAPPS=true
ccache -M 30G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics

# Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines Sepolicy Fix.
make sepolicy
make init
make bootimage
mka nad & # dont remove that '&'
sleep 30m
kill %1
ccache -s
and dont use below codes for first 1 or 2 times, to get ccache uploaded,
