#!/bin/bash
cd /tmp/rom

. build/envsetup.sh
lunch nad_RMX1941-userdebug

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 10G
ccache -o compression=true
ccache -z

make init
make bootimage
make sepolicy

make nad &
sleep 75m
kill %1
ccache -s

up(){
	time rclone copy $1 aosp:ccache/ccache-ci2 -P 
}

ccache -s 
