#!/bin/bash

mkdir -p /tmp/rom/ # Where to sync source.
cd /tmp/rom

repo init -u --no-repo-verify --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest -b 11 -g default,-device,-mips,-darwin,-notdefault

git clone https://github.com/Fraschze97/local_manifest.git --depth=1 -b nusantara11 .repo/local_manifests

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

